// Job Data

let jobs = [
  {
    id: 1,
    companyName: "TechNova Ltd.",
    position: "Frontend Developer",
    location: "Dhaka",
    type: "Full-time",
    salary: "45,000 BDT",
    description: "React developer with 2 years experience.",
    status: "All",
  },
  {
    id: 2,
    companyName: "SoftWhere",
    position: "Backend Developer",
    location: "Remote",
    type: "Part-time",
    salary: "35,000 BDT",
    description: "Laravel and API integration.",
    status: "All",
  },
  {
    id: 3,
    companyName: "DataCore",
    position: "UI/UX Designer",
    location: "Chittagong",
    type: "Contract",
    salary: "40,000 BDT",
    description: "Figma expert with portfolio.",
    status: "All",
  },
  {
    id: 4,
    companyName: "CloudEdge",
    position: "DevOps Engineer",
    location: "Dhaka",
    type: "Full-time",
    salary: "60,000 BDT",
    description: "Linux & Docker experience required.",
    status: "All",
  },
  {
    id: 5,
    companyName: "BrightKind",
    position: "WordPress Developer",
    location: "Remote",
    type: "Freelance",
    salary: "30,000 BDT",
    description: "Custom theme development.",
    status: "All",
  },
  {
    id: 6,
    companyName: "TechBridge",
    position: "Junior JS Developer",
    location: "Sylhet",
    type: "Full-time",
    salary: "28,000 BDT",
    description: "Strong in ES6 and DOM.",
    status: "All",
  },
  {
    id: 7,
    companyName: "NetSolutions",
    position: "QA Engineer",
    location: "Dhaka",
    type: "Full-time",
    salary: "32,000 BDT",
    description: "Manual testing specialist.",
    status: "All",
  },
  {
    id: 8,
    companyName: "FutureTech",
    position: "Mobile App Developer",
    location: "Khulna",
    type: "Contract",
    salary: "50,000 BDT",
    description: "Flutter experience preferred.",
    status: "All",
  },
];

let currentTab = "All";
